<?php
/**
 * Copyright 2020 Vipps
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

declare(strict_types=1);
/** @var $block \Magento\Framework\View\Element\Template */
?>

<div id="vipps-popup-modal" style="display: none;" >
    <h2><?= $block->escapeHtml(__('Updated address?')); ?></h2>
    <p><?= $block->escapeHtml(__("You've updated your addresses in Vipps since your last visit.  Should we update our records?")); ?></p>
    <div class="vipps-address"></div>
    <div class="old-address"></div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Vipps_Login/js/vipps_login_popup": {}
        }
    }
</script>
