<?php
/**
 * Copyright 2019 Vipps
 *
 *    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 *    documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 *    the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 *    and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 *    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 *    TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL
 *    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 *    CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *    IN THE SOFTWARE
 */

declare(strict_types=1);

// @codingStandardsIgnoreFile

/** @var \Vipps\Login\Block\Account\Link $block */

if ($block->isLinked()): ?>

<div class="login-vipps-account">
    <form action="<?php echo $block->getUrl('vipps/login/unlink'); ?>" method="post">
        <div class="icon-login"></div>
        <h3><?= $block->escapeHtml(__('Easier login with Vipps')) ?></h3>
        <p><?= $block->escapeHtml(__('With Vipps you can log in with the pressure of all your devices.
            Your existing username/email and password will continue to work.')) ?></p>
        <button type="submit"
               class="action create primary vipps-btn">
            <?= $block->escapeHtml(__('Stop keep going with')) ?>
            <span class="icon-vipps"></span>
        </button>
    </form>
</div>

<?php else: ?>

    <div class="login-vipps-account">
        <form action="<?php echo $block->getUrl('vipps/login/index'); ?>" method="post">
            <div class="icon-login"></div>
            <h3><?= $block->escapeHtml(__('Easier login with Vipps')) ?></h3>
            <p><?= $block->escapeHtml(__('With Vipps you can log in with the pressure of all your devices.
            Your existing username/email and password will continue to work.')) ?></p>
            <button type="submit"
                   class="action create primary vipps-btn">
                <?= $block->escapeHtml(__('Keep going with')) ?>
                <span class="icon-vipps"></span>
            </button>
        </form>
    </div>

<?php endif?>