<?php
// @codingStandardsIgnoreFile
/** @var \Vipps\Login\Block\Account\Create $block */
?>
<?php if (!$block->isVippsLoggedIn()): ?>
    <div class="login-vipps-holder new-account">
        <div class="login-vipps-holder-text">
            <h2><?= $block->escapeHtml(__('Register')) ?></h2>
            <p><?= $block->escapeHtml(__('Register me by using Vipps')) ?></p>
        </div>
        <?= $block->getChildHtml('vipps_form_register_button') ?>
        <p><?= $block->escapeHtml(__('Or you can use default way')) ?></p>
    </div>
<?php endif; ?>
