<?php
/**
 * Copyright 2019 Vipps
 *
 *    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 *    documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 *    the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 *    and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 *    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 *    TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL
 *    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 *    CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *    IN THE SOFTWARE
 */

declare(strict_types=1);
/** @var \Vipps\Login\Block\Account\Create $block */
?>
<?php if (!$block->isVippsLoggedIn()) : ?>
    <div class="login-vipps-holder new-account" id="register-area">
        <div class="login-vipps-holder-text">
            <h2><?= $block->escapeHtml(__('Register')) ?></h2>
            <p><?= $block->escapeHtml(__('Register me by using Vipps')) ?></p>
        </div>
        <?= $block->getChildHtml('vipps_form_register_button') ?>
        <div class="link-toogle">
            <p><?= $block->escapeHtml(__('... or you can use default way')) ?></p>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Vipps_Login/js/action/register-area": {}
        }
    }
</script>
