<?php
/**
 * Copyright 2020 Vipps
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

/** @var \Vipps\Login\Block\Form\Confirmation $block */

$emails = $block->getEmails();

?>
<div class="block block-customer-login">
    <div class="confirm-page-title">
        <h1><?= $block->escapeHtmlAttr(__('Confirm your email')) ?></h1>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <div class="field note">
            <?= $block->escapeHtml(__('Looks, like your email %1 has been already registered. Confirm your password or send confirmation link to your email.', '<b>' . $block->escapeHtmlAttr(current($emails)) . '</b>'), ['b']) ?>
        </div>
        <form class="form form-login by-mail"
              action="<?= $block->escapeUrl($block->getAjaxEmailConfirmationUrl()) ?>"
              method="post"
              id="verify-email-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset">
                <input type="hidden" name="email" value="<?= $block->escapeHtmlAttr(current($emails)) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email2" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Send confirmation link to email')) ?></span></button></div>
                </div>
            </fieldset>
        </form>
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getAjaxLoginUrl()) ?>"
              method="post"
              id="verify-password-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">

                    <input type="hidden" name="username" value="<?= $block->escapeHtmlAttr(current($emails)) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email1" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('or enter your password')) ?></span></label>
                    <div class="control">
                        <input name="password" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send1"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                </div>
            </fieldset>
        </form>

    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Vipps_Login/js/action/verify": {}
        }
    }
</script>


